version: "3.1"

services:
  db:
    container_name: dblogintemplate
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: LoginTemplate
      MYSQL_ROOT_PASSWORD: superpassword
    volumes:
      - "./data:/var/lib/mysql"